# Generated by Django 2.2 on 2019-05-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
