# Generated by Django 2.2 on 2019-05-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0002_auto_20190505_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ManyToManyField(to='APP01.Goods'),
        ),
    ]
