# Generated by Django 2.2 on 2019-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0004_movies_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
