# Generated by Django 2.2 on 2019-05-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0005_goods_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='emali',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='goods',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movies',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
