# Generated by Django 2.2 on 2019-05-09 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0006_auto_20190509_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('goods', models.ManyToManyField(to='APP01.Goods')),
                ('movies', models.ManyToManyField(to='APP01.Movies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.UserInfo')),
            ],
        ),
    ]
